### ISSUE TITLE
Feature/Wish  List for comming versions

### ISSUE THREAD

**Issue by RUDI-TERROR** [sualko/cloud_bbb#104]
Hello,

First of all I would like to give you a big compliment for your work, it's great to have a BBB extension available for Nextcloud! 

Please understand my "wish list" as a suggestion for future versions from the perspective of a user/teacher:

1. booking system for BBB conferences
     Schedule sessions (with the specification of the planned participants (with the number of voice/video), calendar view for the nextcloud users to avoid overbooking the server
2. invitation link with individual template texts for participants (internal and external)
3. display of the server status (number of current sessions (including participants with voice/video), server load)
4. load balancing in case more than one BBB server is used

I wish you continued success with your app!

Rudi

**Comment by sualko** [comment]
Thanks for your feedback. Just a few notes about it. In general it's easier to manage all feature requests if there is a independent issue for every feature including the required template.

> booking system for BBB conferences

See #45.

> invitation link with individual template texts for participants (internal and external)

Probable #97.

> display of the server status (number of current sessions (including participants with voice/video), server load)

Can you open a new issue and fill the template for this request?

> load balancing in case more than one BBB server is used

This is currently out of scope for this application, because scalelight is working fine. No need to do the work twice. If you have a good counter-argument I would love to hear it in a new issue.

Thanks again for you feedback and have fun with it.
