### ISSUE TITLE
Room Share System

### ISSUE THREAD

**Issue by Smith-fms** [sualko/cloud_bbb#132]
Hey,

It would be nice if we could share a room with normal, moderator or administrator rights.
This should be more convenient for ordinary users to find the rooms.

CU
Rene

**Comment by sualko** [comment]
This is already possible, but the room will not always be visible in the room table. If you want to share it with normal rights, than share a room link. As moderator you also have to share a room link, but the user will join as moderator. If you select the share icon in the moderator share dialog, the room will be shared with admin rights and the room will appear in the room table. The idea is that people are using link files, because they can be accessed also from the app and desktop (if you use the sync client).
