### ISSUE TITLE
Nextcloud 22 compatibility

### ISSUE THREAD

**Issue by mhl66** [sualko/cloud_bbb#169]
**Describe the bug**
Imcompatible with Nextcloud 22, released **July 6th**

**To Reproduce**
1. Start BigBlueButton integration app
2. See server error

**Expected behavior**
1. Start BigBlueButton integration app
2. Don´t see server error

**Screenshots**
n.a.

**System (please complete the following information):**
n.a.
 - App version 1.4.2
 - Nextcloud version 22
 - BigBlueButton version n.a.
 - Is your BigBlueButton instance working with Greenligh**t**? n.a.
 - Did you enter your BBB API url and secret? n.a.

**Nextcloud log:**
n.a.

**Javascript log:**
n.a.

**Additional context**
n.a.

**Comment by joergmschulz** [comment]
now this app is mentioned in the list of incompatible apps. 
There is no official support for NC22 for this app, yet. As soon as there is, we'll notice ....

**Comment by mhl66** [comment]
> now this app is mentioned in the list of incompatible apps.
> There is no official support for NC22 for this app, yet. As soon as there is, we'll notice ....

Instead of indecently closing an eligible issue like this, you should consider following pull request #166

**Comment by joergmschulz** [comment]
#166 doesn't seem to be the only blocker.

**Comment by sualko** [comment]
> Instead of indecently closing an eligible issue like this

That's the point. From my pov this is not eligible, because it's not supported and if you use the search function here you will find other issues with the same problem. So if would be helpful to first check if there are already reports and open a issue afterwards. This helps to save time for the devs. There will be an update soon, but this is an open source application and therefore the maintainers do not have always the time to fix such issue immediately.

**Comment by mhl66** [comment]
It´s ridiculous to mention several (?!) "other issues with the same problem" and to close it **anyway**. NC22 imcompatibility **can not be classified as "not supported"!** - that´s embarrassing. For us, NC without BBB integration is a groupware-showstopper. 

This deluge of useful, but badly supported and erroneous apps is to be considered a serious threat for NC's long-term success in serious environments.

**Comment by sualko** [comment]
If you enable the app it's stated that this app is not compatible and can cause issues. If you update anyway that's not my fault. Most production instances are updating to 20 or 21. Instead of complaining about a free application which is developed in my free time, you should consider contributing.

**Comment by mhl66** [comment]
Try my best to remain constructive: You should consider pull request #166 (see above) - 12 days ago!

**Comment by sualko** [comment]
> 12 days ago!

It's not the only thing I have to consider. Not in my private or business life and also not for new release.

The whole discussion with you is costing time which I don't have, or I could invest in a new release. To be honest, this is not motivation me and it results in a lower priority for this project.

**Comment by mhl66** [comment]
The simple truth: Nextcloud 22 beta 1 was released 2021-05-21, exactly **two months** ago.

The well-known whiny "_it´s-ready-when-it´s-ready_"-attitude ("no time"...) demonstrated above is regrettable, but **not my point**: Nextcloud project should get rid of the exuberant collection of amateur-"supported" apps in the NC app store, to avoid spoiling the trust and usefulness for professional deployment.

**Comment by sualko** [comment]
> to avoid spoiling the trust and usefulness for professional deployment.

A professional deployment should check what they install and maybe use only featured apps. I also don't know any professional setup which upgrades their NC immediately, but that's another point.

> Nextcloud project should get rid of the exuberant collection of amateur-"supported" apps in the NC app store

If you like you can pay me the two days of work and you will have a new version by end of the week. Just write an email to klaus@jsxc.org. This would help to make a "professional" app.

Since this discussion is not useful, I close it for further comments.
