### ISSUE TITLE
Feature requests from the view of a school

### ISSUE THREAD

**Issue by wamagss** [sualko/cloud_bbb#21]
Hello,

I am working at a school with approximately 1600 users (teachers and pupils) and am managing the Nextcloud server for our community. Fortunately I have access to a pool of BBB-servers that can handle all of our users, so there are plans to integrate the usage of BBB inside Nextcloud (similar to the integration that exists for Moodle, but we don't use Moodle...).

My test with the app were successful: really very nice! But there are some essential features missing, preventing us from using the app:

- only certain users or groups (e.g. teachers, admins) can create rooms
- only certain users or groups can start a BBB-session (probably solved with point one)
- no users can join a session if they have no valid Nextcloud account
- no user can hide its identity (nicknames are names from Nextcloud)
- access to a room or session can be limited to a certain group or individual users

There is existing an app for the integration of BBB inside Nextcloud that addresses exactly these points. You can see a demo under https://www.vicole.de/demo, but unfortunately they have not published the app so far and a migration from our Nextcloud to their system is no option for us.

I contacted a developer via their web site. It was the same person that started the discussion here: https://help.nextcloud.com/t/nextcloud-app-for-bigbluebutton-integration/74910. They are planning a release mid-term.

Maybe there is a chance for cooperation...

Greetings, Matthias

**Comment by sualko** [comment]
I split your issues into multiple smaller ones, because it's easier to discuss and keep track.
 
- only certain users or groups (e.g. teachers, admins) can create rooms

:heavy_check_mark: This is already possible if you enable the app only for certain groups.

- only certain users or groups can start a BBB-session (probably solved with point one) :arrow_right: #23
- no users can join a session if they have no valid Nextcloud account :arrow_right: #24
- no user can hide its identity (nicknames are names from Nextcloud)

:heavy_check_mark: This is related to #24, because currently if you are authenticated to Nextcloud you also don't see the "choose a nickname" form

- access to a room or session can be limited to a certain group or individual users :arrow_right: #25

> Maybe there is a chance for cooperation...

I like to help, but I have a lot of other projects beside my everyday job. So you have to wait until I have time, or you can sponsor some of those feature requests to speed up development. I can provide a german invoice, so if you are interested please write an email to klaus@herberth.eu.
