### ISSUE TITLE
Require moderator to open a room

### ISSUE THREAD

**Issue by sualko** [sualko/cloud_bbb#23]
There should be an option that only a moderator (currently owner) of a room can open a room. If other people try to join the room they should be set on hold.

**Comment by Brada65** [comment]
Great idea to implement BBB in NC.
I think this is most important "enhancement" (option), because using links for guest access in unattended rooms represent real danger.
Can you do this option first?

**Comment by sualko** [comment]
> using links for guest access in unattended rooms represent real danger

Which danger are you talking about?

**Comment by Brada65** [comment]
I am working in an immigration agency in Canada, and we are using BBB for online meetings with clients all over the world. We are doing that through moodle, but would like to transfer whole process to NC, and your application is god given for that. Only problem is that in moodle you have option "wait for moderator to join", and nobody can be in a room without moderator, and here during my testing on NC, clients can use the room (once when they have link) even if nobody from officials are there.
You can easily imagine situation where somebody from Peru share that link with relatives in USA to meet them there instead of skype (it is less crowded). Not to mention request from our government that our clients can't use our platform to communicate with each other, just with officials, and that is the reason we need that option turned on.
I don't know much about it but I think that is just one switch off-on, based on settings in moodle. 
![wait for moderator](https://user-images.githubusercontent.com/22346041/81813398-cae71500-94fd-11ea-8e4f-ee3d1f11419f.png)

**Comment by Brada65** [comment]
Sorry, I forgot, it is working with BBB cloud service too (we are using that, not our dedicated BBB server).

**Comment by sualko** [comment]
Ok, I would talk about requirement instead of danger.

> I don't know much about it but I think that is just one switch off-on, based on settings in moodle.

It's just a switch, because someone invested some time in the implementation. Currently I'm busy and have to prioritize my work. For example someone sponsors #19 which will be therefore implemented next. If you also like to sponsor this feature, just write me an email, otherwise you have to white until someone from the community is implementing it (pr welcome), or I have more time. Sorry.

**Comment by jacotec** [comment]
I just discovered this great addon, that's a pretty good idea! :-)

But I deactivated it right away due to this issue, once I found that anyone with a link to my room can start a conference in my room without having me started the room. I need to wait until this is implemented ;-)

**Comment by sualko** [comment]
> I just discovered this great addon, that's a pretty good idea! :-)

Thanks.

 >  need to wait until this is implemented ;-)

No problem. If you like to speed things up: https://www.bountysource.com/issues/91429041-require-moderator-to-open-a-room

**Comment by jacotec** [comment]
> No problem. If you like to speed things up: https://www.bountysource.com/issues/91429041-require-moderator-to-open-a-room

Maybe a company needs the same ... I use BBB for private use and for a non-profit sports club ;-)

**Comment by sualko** [comment]
> Maybe a company needs the same ... 

No doubt about it.

> I use BBB for private use and for a non-profit sports club ;-)

Also individuals and clubs are allowed to support open source with contributions, testing, or a small amount of money :wink:

**Comment by jacotec** [comment]
I'm absolutely with you with testing, be assured once I can use the plugin I'll post issues here ;-)

**Comment by fanf1re** [comment]
From what I am detecting, @sualko can do the fix but he wants some compensation for his time.  Not sure how much that would take, but I suggest if it's an urgent need, have an offline discussion on what it would take to get it now.  I would certainly contribute if I was able to.
