### ISSUE TITLE
BigBlueButton internal server error

### ISSUE THREAD

**Issue by mohanrao83** [sualko/cloud_bbb#26]
Hi,
My Nextcloud server is working fine i installed BigBlueButton successfully from apps store.
after i create room when i access its given internal server error.
also i want a answer from you if possible how many users are connected with nextcloud talk or bigbluebutton.

Pls reply asap.
i m stucked because due to covid19 i want to start this for my college or academy.

Thanks
Mohan Rao

**Comment by sualko** [comment]
I guess you have not added your BBB config to the admin settings. Please check the [README](https://github.com/sualko/cloud_bbb/blob/master/README.md). Otherwise please answer the questions in the newly created [issue template](https://github.com/sualko/cloud_bbb/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).

**Comment by sualko** [comment]
Duplicates are not helpful: https://help.nextcloud.com/t/after-install-bbb-internal-server-error/80092
